version: '2.4'
services:
  mongo_devel:
    container_name: 'mongo-develop'
    image: 'mongo'
    restart: always
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - /mongodb:/data/db
  